[tool.poetry]
name = "pythonproject2"
version = "0.1.0"
description = ""
authors = ["Чухутин Игорь <chukhutinigor@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
black = "^25.9.0"
flake8 = "^7.3.0"
isort = "^6.1.0"
mypy = "^1.18.2"
requests = "^2.32.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
